---

- hosts: all
  tasks:
  
  - name: Update Repository Index
    apt:
      update_cache: yes 

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: install php for apache2 support package
    apt:
      name: libapache2-mod-php
      state: absent 
